export default {
  NOMICS_API_BAE_URL: "https://api.nomics.com/v1",
  NOMICS_API_KEY: "7c4012c0c5ff9aa57afcea4c536c4b6cd9790579", //your-key-here

  CONVERTED_AMOUNT_FRACTION_DIGITS: 2,
  CONVERTED_AMOUNT_ONE_FRACTION_DIGITS: 6,

  EXCHANGE_HISTORY_DURATIONS: [7, 14, 30], //days
  EXCHANGE_HISTORY_DURATIONS_DEFAULT: 7,

  EXCHANGE_HISTORY_REPORT_TYPE_DEFAULT: "table",
  EXCHANGE_HISTORY_REPORT_TYPE_RATE_DIGITS: 6,

  CONVERSION_HISTORY_DB_NAME: "ConversionHistory"
};
